### ISSUE TITLE
AttributeError: 'TfidfTransformer' object has no attribute '_idf_diag'

### ISSUE THREAD

**Issue by githubmorgan** [ing-bank/EntityMatchingModel#16]
Hi,

Am trying the example and when i get to  

_**# instantiate a matching model
n**m = PandasEntityMatching({
    'name_only': True,
    'preprocessor': 'preprocess_merge_abbr',
    'indexers': [{
        'type': 'cosine_similarity',
        'tokenizer': 'words',
        'ngram': 1,
        'num_candidates': 5,
        'cos_sim_lower_bound': 0.2,
    }],
    'supervised_on': True,
    'supervised_model_filename': 'sem_nm.pkl',
    'supervised_model_dir': '.',
})
nm.fit(gt)

i'm getting the following error...

AttributeError                            Traceback (most recent call last)
Cell In[10], [line 19](vscode-notebook-cell:?execution_count=10&line=19)
      [2](vscode-notebook-cell:?execution_count=10&line=2) nm = PandasEntityMatching({
      [3](vscode-notebook-cell:?execution_count=10&line=3)     'name_only': True,
      [4](vscode-notebook-cell:?execution_count=10&line=4)     'preprocessor': 'preprocess_merge_abbr',
   (...)
     [14](vscode-notebook-cell:?execution_count=10&line=14)     'supervised_model_dir': '.',
     [15](vscode-notebook-cell:?execution_count=10&line=15) })
     [17](vscode-notebook-cell:?execution_count=10&line=17) # matching of names is done against the ground-truth dataset (gt).
     [18](vscode-notebook-cell:?execution_count=10&line=18) # for this we need to fit our indexers to the ground-truth.
---> [19](vscode-notebook-cell:?execution_count=10&line=19) nm.fit(gt)

File ~/.local/lib/python3.10/site-packages/emm/pipeline/pandas_entity_matching.py:251, in PandasEntityMatching.fit(self, ground_truth_df, copy_ground_truth)
    [249](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/emm/pipeline/pandas_entity_matching.py:249) if copy_ground_truth:
    [250](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/emm/pipeline/pandas_entity_matching.py:250)     self.ground_truth_df = ground_truth_df.copy()
--> [251](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/emm/pipeline/pandas_entity_matching.py:251) self.model = self.pipeline.fit(ground_truth_df)
    [252](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/emm/pipeline/pandas_entity_matching.py:252) self.n_ground_truth = len(ground_truth_df)
    [254](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/emm/pipeline/pandas_entity_matching.py:254) timer.log_param("n", self.n_ground_truth)

File ~/.local/lib/python3.10/site-packages/sklearn/base.py:1473, in _fit_context.<locals>.decorator.<locals>.wrapper(estimator, *args, **kwargs)
   [1466](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/sklearn/base.py:1466)     estimator._validate_params()
   [1468](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/sklearn/base.py:1468) with config_context(
   [1469](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/sklearn/base.py:1469)     skip_parameter_validation=(
   [1470](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/sklearn/base.py:1470)         prefer_skip_nested_validation or global_skip_validation
...
---> [79](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/emm/indexing/pandas_normalized_tfidf.py:79) idf_diag = self._tfidf._idf_diag
     [80](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/emm/indexing/pandas_normalized_tfidf.py:80) idf_diag = idf_diag - scipy.sparse.diags(np.ones(idf_diag.shape[0]), shape=idf_diag.shape, dtype=self.dtype)
     [81](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/mnt/c/Users/morga/source/repos/wsl_matching/~/.local/lib/python3.10/site-packages/emm/indexing/pandas_normalized_tfidf.py:81) self._tfidf._idf_diag = idf_diag

AttributeError: 'TfidfTransformer' object has no attribute '_idf_diag'

**Comment by mbaak** [comment]
Hello, thanks for posting. 
Which version of sklearn are you using? Then I can try to reproduce the issue.

**Comment by githubmorgan** [comment]
Hi,

I’m using 1.5.0

Cheers
Morgan

**Comment by mbaak** [comment]
Apologies for the delay. I can reproduce it - indeed it's due to changes in sklearn v1.5.0.
I'll look into how to fix this.

**Comment by githubmorgan** [comment]
Many thanks.

**Comment by vikas-tripathi** [comment]
I am having the same issue.. Many thanks for looking into it.  Can you also let me know for which version of sklearn does it work before?

**Comment by mbaak** [comment]
We're looking at it ...
For now using: scikit-learn < 1.5.0 
should solve it.
(I may just a quick patch release with this constraint for now.)

**Comment by mbaak** [comment]
We've fixed this issue. The code now works with both sklearn < 1.5 and later versions of sklearn.
Fixed in v2.1.2
